### ISSUE TITLE
Accık da gtk katsak?

### ISSUE THREAD

**Issue by Zaryob** [examachine/pisi#103]
Pisi icin ongorulen developing map'te QT gui ve QT ile yazılmış bir PİSİMAT veya Pisido onerilmis. Ben diyorum ki QT iyi hoş ama qt'ye çakılıp kalmasak da gtk tabanlı arayüz filan da yapılsa olmaz mı?

**Comment by examachine** [comment]
gtk tabanli ui yapilabilir ama bunun yeri pisi projesi degil
