### ISSUE TITLE
MacOS hakkinda onerim var

### ISSUE THREAD

**Issue by Zaryob** [examachine/pisi#106]
Pisinin içerisinde (pisi.archive veya pisi.files modullerinden birindeydi simdi bakamayacagim tekrar) kodda os.chdir("/") yapip butun arsiv içeriğini oraya kusuyor. Bunu kullanarak MacOS'da teorik olarak kurulum saglanabilir. Home dizini icerisinde .pisi diye bir dosya acilip oranin kok dizin olarak gosterilmesi yetecektir. MacOs icin olan System.base paketlerini pisinin bagimliliklari yaparsak eger pisi MacOS uzerinde  calisabilir. Hatta brew gibi linuxlarda da kullanilabilen bir paket yoneticisi bile olabilir

**Comment by Zaryob** [comment]
Bu arada son 4 issue'da turkce yazmami mazur gorurursunuz umarim 😊

**Comment by examachine** [comment]
Mac OS'de zaten calisiyor pisi. User directory icin de ayri issue var. Issue'lara baktigina emin misin? Issue'lara bakmadan issue acmayin.
