### ISSUE TITLE
İndex alimi sirasinda olusan bir bug

### ISSUE THREAD

**Issue by Zaryob** [examachine/pisi#107]
Bos bir klasorun içerisinde index almaya calisinca pisi sanki icerde binary veya spec varmis gibi davranip index dosyasi yaratiyor. Sadece bos bir iki dosya olusuyor ama bence biraz goz zevkini hirpalayan bir bug. index.py icerisinde o bugu cozmeye calisacagim.

**Comment by examachine** [comment]
eger indexleyecek birsey yoksa bu bir hata mesaji vermeli. hata raporlarini ingilizce yazabilirsiniz.
