### ISSUE TITLE
. 

### ISSUE THREAD

**Issue by Zaryob** [examachine/pisi#109]

**Comment by AquilaNipalensis** [comment]
or it does not have to be a python code. We can even write bash scripts with an afterinstall module.

Ya da python kodu olmak zorunda degil. Bash scripti calistirmayi bir afterinstall modulu ile saglayabiliriz.

**Comment by examachine** [comment]
I think it should be python. Python is futuristic, it's great. I made the right design decision after all. :P 

Good thinking brother. :) Yes, we should definitely drop weird dependencies if we can. 

A new API in actions.py like configure sounds like a good idea. But we have to be certain that we can cover this within actions.py or if we need a new daemon. Writing a daemon in python is EASY, doesn't require a lot of kludge like comar seems to be. We can write as many daemons or as extra system tools as necessary. Let's keep an open mind and do the right thing.

**Comment by examachine** [comment]
So, we have top level actions for building, and installing, and maybe we also need some hooks for
 - configuring package during installation
 - boot-time configuration or whatever is needed

Not sure what exactly we need or all the things that comar already does with regards to pkg config. Just thinking in terms of debconf: 
https://wiki.debian.org/debconf

In COMAR we don't ask the user any questions and store any information about such choices, so that sounds like the only place where it truly differs, and we always prefer auto configuration in Pardus distro -- no hard choices for the user. So that's like the only two things that differ in practice from debconf. Is that true for also PISI Linux distro?

**Comment by AquilaNipalensis** [comment]
@examachine We can use curses library for debconf type gui. And we can  store by types. Example if there is any alternative for it we can say 'which one you sellect for using' and if user want select new package we run config script or not want use new package user select it and go on using

**Comment by AquilaNipalensis** [comment]
And we can change our selects.

**Comment by AquilaNipalensis** [comment]
I work for it now.

**Comment by AquilaNipalensis** [comment]
I write a conf manager. It run into pisi. I style a [curses](https://docs.python.org/3/howto/curses.html) library for compabilty. I write a pisiconfdb. But I dont understand. How we can make separate programs that work the same. Example there was lightdm in our system. And we want install gdm. How we can this work the same gdm. Which one you want install????

**Comment by examachine** [comment]
There is an issue about an alternatives system. About an implementation of port select command.

**Comment by examachine** [comment]
birader sen neye istinadan pisi'yi fork edip ismimi cikariyorsun? derhal bu fikir hirsizligina son verin. kafayi mi yediniz?

**Comment by Zaryob** [comment]
Merhaba Eray Özkural
Projeye gerçek manada yardım etmek istedim. Ancak herhangi bir ilerleme olmamasına mutakiben pardus 2011 tarafından bırakılan pisi-2.4 forklayarak kendi forkumu oluştyrdum. Bütünü ile GPL lisanslarına uygun yapılan bir fork işlemi. Fikir hırsızlığı yok. Öncelikle özgür yazılım nedir onu bir öğrenin ardından kafayı yiyip yemediğimi sorgulayabilirsiniz.

**Comment by examachine** [comment]
Fork ettiginiz versiyon orijinal pardus takiminda yer alan iftiraci ve kumpasci bir kisinin benim account'umu ve adimi kaynak dosyalarindan cikarmasi sonucu pisi'nin %85'ini yazmisken sanki siradan bir contributor gibi gozukmeme yol acan bir tahrifat ve ozgecmisime yapilan bir saldiriyi icermektedir. Bu adilige ortak oluyorsunuz. Derhal o paketi kaldirin. Gormeyecegim onu.

**Comment by examachine** [comment]
Bir daha yazayim acikca anlasilsin, saniyorum caglar beyefendi pisi'yi tezine koymus orada da katkisini abartabilmek icin ilk yazarin kim oldugunu GIZLEME geregi duymustur. Buna intihal deniyor. Eger bu kepazelige ortak olursaniz buyuk bir hata islemis olursunuz.

**Comment by examachine** [comment]
AUTHORS dosyasini buradaki development branch'den alirsaniz, her dosyanin basindaki copyright ve Authors satirlarini TAHRIF ETMEDEN kopyalarsaniz, ve paketin adini pisi-sulo gibi pisi- prefix'i ile degistirirseniz istediginiz gibi fork edebilirsiniz. Buna izin veririm. Ama bu turlu benim sahsima ve tarihceme hakarettir. Ticari zarar veriyorsunuz su anda bana.

**Comment by examachine** [comment]
Ayrica GNU Pardus chatroom'unda pisi linux icin cop denmis, ayiptir, bu tur saldirgan ve cocukca davranislar ozgur yazilim ruhuna uymamaktadir, derhal mentor olarak sosyopatlari secmekten vazgeciniz. Ve pisi linux grubuna anonim troll gonderiyorsaniz, eger o tuhaf kimseler sizinle iletisim icerisindeyse, geri gelmemelerini soyleyiniz.
