### ISSUE TITLE
spec'lerden history kısmının kaldırılması

### ISSUE THREAD

**Issue by aydemir** [examachine/pisi#58]
scm lerde tüm değişiklikler varken spec'te history tutulması archaic methods gibi

**Comment by examachine** [comment]
ok dusunelim ama backwards compatibility icin bu tur degisiklikler hakkinda cekimserim

**Comment by examachine** [comment]
bunu yapmamaya karar verdim cunku backwards compatibility'i cok kirar ve o dosyalar o kadar buyuk degil changelog'u pisi-gui'den gorebilmek de iyi olurdu. kullanici icin iyi birsey aslinda.
